version: "1.0"

services:
  postfix:
    container_name: "postfix"
    volumes:
    - ./conf/postfix:/etc/postfix
    build: .
    ports:
      - 25:25
    networks:
      - LMTP
  
  dovecot:
    container_name: "Dovecot"
    image: dovecot/dovecot:2.3.21.1
    volumes:
    - ./mail_data:/home
    - ./conf/dovecot:/etc/dovecot
    ports:
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 587:587
    networks:
      - LMTP

networks:
  LMTP:
    driver: bridge      

# POP3 on 110, TLS 995
# IMAP on 143, TLS 993
# Submission on 587
# LMTP on 24
# ManageSieve on 4190